version: "3"

services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: solinftec
      POSTGRES_DB: stock
    volumes:
      - /var/lib/postgresql/data

  apiuser:
    image: "user:v1"
    ports:
      - 8081:8081
    depends_on:
      - database
    environment:
      DB_URL: jdbc:postgresql://database:5432/postgres
  apistocks:
    image: "stock:v1"
    ports:
      - 8083:8083
    depends_on:
      - apiuser
      - database
    environment:
      DB_URL: jdbc:postgresql://database:5432/stock
